---
 - hosts: buildservers
   tasks:
     - name: Fetch the file from the javabuildserver to master
       fetch: src=/home/devopsadmin/jenkins/workspace/Java-Mvn-Build-Docker-Pipeline/target/mvn-hello-world.war dest=buffer/ flat=yes
       when: "{{ inventory_hostname == 'javabuildserver' }}"

     - name: Copy the file from master to devappserv
       copy: src=buffer/mvn-hello-world.war dest=/opt/tomcat/webapps/
       when: "{{ inventory_hostname == 'devappserv' }}"
